name: CI
on:
  pull_request:
  push:
    branches-ignore:
      - "graphite-base/**"
  workflow_dispatch:
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  cargo:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          nix_version: "2.31.2"
          nix_conf: |
            accept-flake-config = true
            fallback = true
      - name: Format
        run: nix develop -c cargo fmt --all --check
      - name: Clippy
        run: nix develop -c cargo clippy --workspace --all-targets --all-features
      - name: Test
        run: nix develop -c cargo test --workspace --all-features
